/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedModeRouteImport } from './routes/embed.$mode'
import { Route as AssistantModeRouteImport } from './routes/assistant.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedModeRoute = EmbedModeRouteImport.update({
  id: '/embed/$mode',
  path: '/embed/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantModeRoute = AssistantModeRouteImport.update({
  id: '/assistant/$mode',
  path: '/assistant/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant/$mode': typeof AssistantModeRoute
  '/embed/$mode': typeof EmbedModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant/$mode': typeof AssistantModeRoute
  '/embed/$mode': typeof EmbedModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant/$mode': typeof AssistantModeRoute
  '/embed/$mode': typeof EmbedModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistant/$mode' | '/embed/$mode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistant/$mode' | '/embed/$mode'
  id: '__root__' | '/' | '/assistant/$mode' | '/embed/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantModeRoute: typeof AssistantModeRoute
  EmbedModeRoute: typeof EmbedModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$mode': {
      id: '/embed/$mode'
      path: '/embed/$mode'
      fullPath: '/embed/$mode'
      preLoaderRoute: typeof EmbedModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$mode': {
      id: '/assistant/$mode'
      path: '/assistant/$mode'
      fullPath: '/assistant/$mode'
      preLoaderRoute: typeof AssistantModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantModeRoute: AssistantModeRoute,
  EmbedModeRoute: EmbedModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
